USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS AB_TRIAL_ADMIN_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS AB_TRIAL_ADMIN;

CREATE SCHEMA IF NOT EXISTS AB_TRIAL_ADMIN.SCHEMACHANGE;
