USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS AB_TRIAL_DEV_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS AB_TRIAL_UAT_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE WAREHOUSE IF NOT EXISTS AB_TRIAL_PROD_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS AB_TRIAL_DEV;
CREATE DATABASE IF NOT EXISTS AB_TRIAL_UAT;
CREATE DATABASE IF NOT EXISTS AB_TRIAL_PROD;

CREATE SCHEMA IF NOT EXISTS AB_TRIAL_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS AB_TRIAL_DEV.STAGING;
CREATE SCHEMA IF NOT EXISTS AB_TRIAL_DEV.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS AB_TRIAL_DEV.MARTS;
CREATE SCHEMA IF NOT EXISTS AB_TRIAL_DEV.AUDIT;

CREATE SCHEMA IF NOT EXISTS AB_TRIAL_UAT.RAW;
CREATE SCHEMA IF NOT EXISTS AB_TRIAL_UAT.STAGING;
CREATE SCHEMA IF NOT EXISTS AB_TRIAL_UAT.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS AB_TRIAL_UAT.MARTS;
CREATE SCHEMA IF NOT EXISTS AB_TRIAL_UAT.AUDIT;

CREATE SCHEMA IF NOT EXISTS AB_TRIAL_PROD.RAW;
CREATE SCHEMA IF NOT EXISTS AB_TRIAL_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS AB_TRIAL_PROD.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS AB_TRIAL_PROD.MARTS;
CREATE SCHEMA IF NOT EXISTS AB_TRIAL_PROD.AUDIT;
